# Generated by Django 4.0.4 on 2022-05-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_nr', models.CharField(help_text='įrašykite automobilio valstybini numerį', max_length=20, verbose_name='Valstybinis numeris')),
                ('vin_code', models.CharField(help_text='įrašykite automobilio 17 simbolių VIN kodą', max_length=17, verbose_name='VIN kodas')),
                ('client', models.CharField(max_length=200, verbose_name='kliento vardas')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200, verbose_name='marke')),
                ('model', models.CharField(max_length=200, verbose_name='modelis')),
                ('year', models.IntegerField(default=1997, verbose_name='pagaminimo metai')),
                ('engine', models.CharField(default='super variklis', max_length=200, verbose_name='variklis')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='Uzsakymo data')),
                ('sum_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='kaina')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymai', to='carservice.car', verbose_name='uzsakymas')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='pavadinimas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='kaina')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='kiekis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='kaina')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymai', to='carservice.order', verbose_name='uzsakymas')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymu_eilutes', to='carservice.service', verbose_name='uzsakymo eilute')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='carservice.carmodel', verbose_name='automobilis'),
        ),
    ]
