# Generated by Django 4.0.4 on 2022-05-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modelizzzzzz', 'verbose_name_plural': 'Modeliaiaiaiaiaia'},
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masinos', to='carservice.car', verbose_name='masina'),
        ),
    ]
