# Generated by Django 4.0.4 on 2022-05-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0002_alter_carmodel_options_alter_order_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobilių modeliai'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'užsakymo eilutė', 'verbose_name_plural': 'užsakymų eilutės'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
    ]
