# Generated by Django 4.0.4 on 2022-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0003_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('g', 'gautas'), ('p', 'pradetas vykdyti'), ('b', 'baigtas'), ('s', 'sustabdytas')], db_index=True, default='a', max_length=1, verbose_name='statusas'),
        ),
    ]
