# Generated by Django 4.0.4 on 2022-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0005_alter_orderline_order_alter_orderline_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures', verbose_name='Automobilis'),
        ),
    ]
