# Generated by Django 4.0.4 on 2022-05-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carservice', '0007_order_owner_alter_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Uzsakymo įvykdymo data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='savininkas'),
        ),
    ]
