# Generated by Django 4.0.4 on 2022-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0008_order_due_back_alter_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Uzsakymo įvykdymo data'),
        ),
    ]
